### ISSUE TITLE
Create new journeys

### ISSUE THREAD

**Issue by gregtyler** [ministryofjustice/moj-ds-accessibility-audit#27]
The following journeys have been suggested to cover usage of our components:

- [x] Create an account
  - Password reveal #17 
- [x] Find a grant: navigate to the grants page, find some grants matching a filter and select some #28
  - Primary navigation
  - Filter
  - Filter layout
  - Button menu
  - Pagination
  - Tag
  - Multi-select
- [x] Look at a grant: switch to your organisation, open a grant and review its (tabbed) details #30
  - Organisation switcher
  - Ticket panel
  - Search
  - Sub-navigation
  - Timeline
  - Badge
  - Sortable table
- [x] Edit a grant: Change some details of a grant #31
  - Page header actions
  - Form validator
  - Rich text editor
  - Currency input
  - Banner
- [x] Provide some documents: Search for a grant to add files to, and add some #32
  - Search
  - File upload
  - Multi file upload
  - Banner
- [x] Chat to us: Select the "chat to us" page, read our message, send us a new one #33 
  - Messages
  - Notification badge
  - Side navigation
- [x] Review a task list: Look at your task list and... select an action from the identity bar..? #34 
  - Task list
  - Identity bar
  - Button menu
  - Add another

[Spreadsheet tracking coverage](https://docs.google.com/spreadsheets/d/1yALZAJSRMbnl-zV-pcoHVycAeQ5XcIPMOouKMqiETMU/edit#gid=0)

**Comment by gregtyler** [comment]
All moved to individual tickets 🎉
